### ISSUE TITLE
Authentication issue while running wps_resolve_rules

### ISSUE THREAD

**Issue by sum1lim** [pacificclimate/sandpiper#9]
Running `wps_resolve_rules` process of #8 results in the following authentication error.

```
127.0.0.1 - - [27/Jul/2020 11:01:05] "POST /wps HTTP/1.1" 200 -
127.0.0.1 - - [27/Jul/2020 11:01:48] "GET /wps?service=WPS&request=GetCapabilities&version=1.0.0 HTTP/1.1" 200 -
127.0.0.1 - - [27/Jul/2020 11:01:48] "GET /wps?service=WPS&request=DescribeProcess&version=1.0.0&identifier=all HTTP/1.1" 200 -
2020-07-27 11:01:48 INFO: Reading /home/sangwonl/Desktop/sandpiper/tests/data/rules_small.csv
2020-07-27 11:01:48 INFO: Reading /home/sangwonl/Desktop/sandpiper/tests/data/rules_small.csv
2020-07-27 11:01:48 INFO: Building parse tree
2020-07-27 11:01:48 INFO: Building parse tree
2020-07-27 11:01:48 INFO: Collecting variables
2020-07-27 11:01:48 INFO: Collecting variables
2020-07-27 11:01:48 INFO:
2020-07-27 11:01:48 INFO:
2020-07-27 11:01:48 INFO: Translating variables for query
2020-07-27 11:01:48 INFO: Translating variables for query
2020-07-27 11:01:48 INFO: Collecting models
2020-07-27 11:01:48 INFO: Collecting models
2020-07-27 11:01:48 INFO: Fetching data for temp_djf_iamean_s0p_hist
2020-07-27 11:01:48 INFO: Fetching data for temp_djf_iamean_s0p_hist
2020-07-27 11:01:48 WARNING: Error: (psycopg2.OperationalError) fe_sendauth: no password supplied

(Background on this error at: http://sqlalche.me/e/13/e3q8) while collecting variable: temp_djf_iamean_s0p_hist
2020-07-27 11:01:48 WARNING: Error: (psycopg2.OperationalError) fe_sendauth: no password supplied

(Background on this error at: http://sqlalche.me/e/13/e3q8) while collecting variable: temp_djf_iamean_s0p_hist
Traceback (most recent call last):
  File "/home/sangwonl/Desktop/sandpiper/venv/lib/python3.7/site-packages/pywps/app/Process.py", line 249, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/home/sangwonl/Desktop/sandpiper/sandpiper/processes/wps_resolve_rules.py", line 119, in _handler
    rules, date_range, region, ensemble, connection_string, log_level
  File "/home/sangwonl/Desktop/sandpiper/venv/lib/python3.7/site-packages/p2a_impacts/resolver.py", line 78, in resolve_rules
    if var is not None:
UnboundLocalError: local variable 'var' referenced before assignment
```

**Comment by nikola-rados** [comment]
So I have a `.pgpass` file in my home directory that handles the auth. I think this is a documentation issue rather than a code issue. Try creating/modifying a `.pgpass` file to include the `ce_meta` database auth.
